### ISSUE TITLE
Enhancement : modification of parameters take effects after relauching XyGrib

### ISSUE THREAD

**Issue by dominiquehausser** [opengribs/XyGrib#110] opened 2018-09-24 10:06 UTC
Is easily feasible that when modifiying a parameter it take effect immediatly whithout restarting the application ?

**Comment by norulz** [comment] 2018-09-24 10:32
Already fixed and will be in next release

**Comment by dominiquehausser** [comment] 2018-09-24 10:37
Does not work for me even with build after commit 300.

**Comment by did-g** [comment] 2018-09-24 12:05
Hi,

Are you doing a make clean first?

**Comment by dominiquehausser** [comment] 2018-09-24 14:48
Graphical and units. I did not check the language.

**Comment by did-g** [comment] 2018-09-24 16:47
Hi,
units wasn't impacted, something else is going on, I did retest master (your version)  and it works for me on unbuntu 18.04 64 bits. 
Could you 
- double check you aren't running an older installed version.
- run a bisect if you have a known version working for you.

**Comment by dominiquehausser** [comment] 2018-09-24 17:21
Hello,
Thanks for your response.

I recheck again for graphical parameters, this is OK (I probably mixed version as you suggest).

Problem remain with units.

Units parameter is not changing (this was the reason of my issue as I was looking about scales) without restarting the app. I forgot that corrections were done for graphical also to be dynamic and not only after restarting the app (as I quite rarely change these graphical parameters, being happy with those I have tuned a couple of years ago).

Just for my culture, even with my age I a still a beotian in writing programmes, I imagine that run a bisect is to find out where could be in the code a problem

**Comment by norulz** [comment] 2018-09-24 18:28
Hi @did-g 
I checked Windows and Ubuntu. In Ubuntu the color scale does not change when a unit is changed (i.e. wind from knots to m/s). In Windows the color scale does update when saving a new unit change.

**Comment by did-g** [comment] 2018-09-24 19:43
Hi
yep, I'm seeing it too, I was looking at the wrong panel.
On window is closing color scale panel update Weather Map Options menu? It isn't on Linux.

**Comment by did-g** [comment] 2018-09-24 19:51
@dominiquehausser 
Yes it's what bisect do. You have a broken version and a working one, git bisect binary searches between the two for finding the culprit, very powerful tool for regression.

cf. git help bisect

**Comment by dominiquehausser** [comment] 2018-09-24 20:09
Thanks.

**Comment by norulz** [comment] 2018-09-24 21:34
The problem seems to be related to `void ColorScaleGraph::paintEvent (QPaintEvent *)` in ColorScaleWidget.cpp.

In Windows the OS triggers this event even when you thing of touching anything!
In Linux it appears not be triggers almost at all apparently only internally while windows gets external triggers as well.

I'm off sailing until Friday!

**Closed** 2018-09-28 15:20 UTC
